os: linux

dist: xenial

language: node_js

node_js:
  - '8'
  - '10'
  - '12'
  - 'lts/*'

git:
  depth: 3

cache:
  - npm
  - directories:
      - .eslintcache

script:
  - npm run lint
  - npm test
